Repository reactjs/pt-PT.reactjs.org, pull requests merged in 2019-02, with the labels that each got.

#5 Translation of error-decoder
  content/docs/error-decoder.md
Labels: needs +1

#6 Hello world
  content/docs/hello-world.md
Labels: needs +1

#3 Translation of getting-started.md
  content/docs/getting-started.md
Labels: 🌐 translated

#12 Translation of faq-build.md
  content/docs/faq-build.md
Labels: needs +1

#7 Translation of reference-react-dom-server.md
  content/docs/reference-react-dom-server.md
Labels: changes already resolved - waiting for reviewers, needs review

#11 Translation of cdn-links
  content/docs/cdn-links.md
Labels: 🌐 translated
